version: "3"
services:
  server:
    build:
      dockerfile: "./local/Dockerfile"
      context: "."
    ports:
      - "8080:8080"
    volumes:
      - ./local:/local
    command: sh -c './wait-for.sh elasticsearch:9200 -t 60 -- /grafeas-server --config /local/config.yaml'
    depends_on:
      - elasticsearch
  elasticsearch:
    build: "./local/elasticsearch"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    mem_limit: 1GB
  kibana:
    image: bitnami/kibana:7.9.3
    ports:
    - 5601:5601
    environment:
      - KIBANA_ELASTICSEARCH_URL=elasticsearch
    depends_on:
      - elasticsearch
